# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 437e6b2f4398f496a0205af05aaaacfe862390fa248fb47344130c9e572895045a43d3b877ce18e3c589d333a739c3ca059be63ab1d226b0a66326da2e28c64d

test:
  secret_key_base: 3b4a043a483a83577f611b1f02436f77832d86a9bbed0a0cda907de4e69a9b08e8ef31dd4471d6e1340e95d14ab5292c65948aa5dcc19f01db3e4986582c7e50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
